version: "3.9"
services:
  web:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    entrypoint: "python3 src/run.py"
    ports:
      - "5000:5000"
