from decouple import config

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_KEY_ACCESS = config("AWS_SECRET_ACCESS_KEY")
AWS_REGION = config("AWS_REGION")
S3_BUCKET_NAME = config("S3_BUCKET_NAME")
